// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DisplayAnnecdotesAboutController from "./display_annecdotes_about_controller"
application.register("display-annecdotes-about", DisplayAnnecdotesAboutController)

import DisplayDescriptionProjectsController from "./display_description_projects_controller"
application.register("display-description-projects", DisplayDescriptionProjectsController)

import DisplayDescriptionResumeController from "./display_description_resume_controller"
application.register("display-description-resume", DisplayDescriptionResumeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavbarPropertiesController from "./navbar_properties_controller"
application.register("navbar-properties", NavbarPropertiesController)
