meta_product_name: "Benoit Brandt web developer full-stack"
meta_title: "Benoit Brandt web developer full-stack - Ruby on rails "
meta_description: "After finished le Wagon bootcamp I'm looking forward to still continu to learn my coding journey"
meta_image: "Profil.jpg" # should exist in `app/assets/images/`
twitter_account: "@benoilte"   # required for Twitter Cards
