meta_product_name: "Benoit Brandt web developer full-stack"
meta_title: "Benoit Brandt web developer full-stack - Ruby on rails - Lausanne switzerland "
meta_description: "Recently graduated from Le Wagon development web Bootcamp, I'm actively looking for a first working experience to boost my coding progress. In parallel to my job research, I keep practicing programming with personal projects and by self-taught on different learning platforms"
meta_image: "Profil.jpg" # should exist in `app/assets/images/`
twitter_account: "@benoilte"   # required for Twitter Cards
